# Generated by Django 3.0.2 on 2020-01-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('cpt_id', models.AutoField(db_column='CPT_ID', primary_key=True, serialize=False)),
                ('t_cpt_num', models.CharField(blank=True, db_column='T_CPT_NUM', max_length=50, null=True, unique=True)),
                ('t_name', models.CharField(db_column='T_NAME', max_length=255)),
                ('n_solde_avail', models.FloatField(db_column='N_SOLDE_AVAIL')),
                ('n_solde_locked', models.FloatField(db_column='N_SOLDE_LOCKED')),
                ('t_type', models.CharField(db_column='T_TYPE', max_length=255)),
                ('t_banque', models.CharField(db_column='T_BANQUE', max_length=255)),
                ('d_inactive', models.DateField(blank=True, db_column='D_INACTIVE', null=True)),
            ],
            options={
                'db_table': 'ACCOUNTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('cal_id', models.AutoField(db_column='CAL_ID', primary_key=True, serialize=False)),
                ('d_date', models.DateField(db_column='D_DATE')),
            ],
            options={
                'db_table': 'CALENDAR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatAssign',
            fields=[
                ('cat_assign_id', models.AutoField(db_column='CAT_ASSIGN_ID', primary_key=True, serialize=False)),
                ('t_desc', models.CharField(db_column='T_DESC', max_length=1000)),
                ('d_start', models.DateField(blank=True, db_column='D_START', null=True)),
                ('d_end', models.DateField(blank=True, db_column='D_END', null=True)),
                ('n_val_min', models.FloatField(blank=True, db_column='N_VAL_MIN', null=True)),
                ('n_val_max', models.FloatField(blank=True, db_column='N_VAL_MAX', null=True)),
            ],
            options={
                'db_table': 'CAT_ASSIGN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(db_column='CAT_ID', primary_key=True, serialize=False)),
                ('t_cat_name', models.CharField(db_column='T_CAT_NAME', max_length=255)),
            ],
            options={
                'db_table': 'CATEGORIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CbOwner',
            fields=[
                ('cbowner_id', models.AutoField(db_column='CBOWNER_ID', primary_key=True, serialize=False)),
                ('t_cb_num', models.CharField(db_column='T_CB_NUM', max_length=255)),
                ('t_cb_owner', models.CharField(db_column='T_CB_OWNER', max_length=255)),
            ],
            options={
                'db_table': 'CB_OWNER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CbPlan',
            fields=[
                ('cb_plan_id', models.AutoField(db_column='CB_PLAN_ID', primary_key=True, serialize=False)),
                ('n_year', models.IntegerField(db_column='N_YEAR')),
                ('n_month', models.IntegerField(db_column='N_MONTH')),
                ('d_start', models.DateField(db_column='D_START')),
            ],
            options={
                'db_table': 'CB_PLAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('op_id', models.AutoField(db_column='OP_ID', primary_key=True, serialize=False)),
                ('t_op_type', models.CharField(db_column='T_OP_TYPE', max_length=50)),
                ('d_date', models.DateField(db_column='D_DATE')),
                ('t_desc', models.CharField(blank=True, db_column='T_DESC', max_length=255, null=True)),
                ('t_bankop_key', models.CharField(blank=True, db_column='T_BANKOP_KEY', max_length=50, null=True)),
                ('n_value', models.FloatField(db_column='N_VALUE')),
                ('t_comment', models.CharField(blank=True, db_column='T_COMMENT', max_length=1000, null=True)),
                ('n_solde', models.FloatField(blank=True, db_column='N_SOLDE', null=True)),
                ('n_match_id', models.IntegerField(blank=True, db_column='N_MATCH_ID', null=True)),
            ],
            options={
                'db_table': 'OPERATIONS',
                'managed': False,
            },
        ),
    ]
